"""allow baseline file duplicates

Revision ID: a2edc11bfc9e
Revises: 281f83a1743d
Create Date: 2026-08-27 23:10:37.016357
"""

from collections.abc import Sequence

from alembic import op

revision: str = "a2edc11bfc9e"
down_revision: str | None = "281f83a1743d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_files_sha256"), table_name="book_files")
    op.create_index(op.f("ix_book_files_sha256"), "book_files", ["sha256"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_files_sha256"), table_name="book_files")
    op.create_index(op.f("ix_book_files_sha256"), "book_files", ["sha256"], unique=1)
    # ### end Alembic commands ###
